[project]
name = "understanding-hf-kernel-builder"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "huggingface-hub>=0.32.2",
    "kernels>=0.5.0",
    "torch==2.6.0",
]
